language: php
dist: trusty
php:
  - 7.2
  - 7.1.9

cache:
    apt: true
    ccache: true

before_script:
    - ccache --version
    - ccache --zero-stats
    - export USE_CCACHE=1


script:
    - ./compiler.sh

after_success:
    - ccache --show-stats