language: php
sudo: false

addons:
  apt:
    packages:
      - libopenblas-dev

php:
  - 7.0
  - 7.1
  - 7.2
  - nightly

cache:
  apt: true
  ccache: true

before_script:
  - ccache --version
  - ccache --zero-stats
  - export USE_CCACHE=1
  - phpize
  - ./configure
  - make
  - make install
  - echo "extension=phpsci.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script:
  - REPORT_EXIT_STATUS=1 php ./run-tests.php -P -q --show-diff

after_success:
  - ccache --show-stats
