site_name: PHPSci CArray
theme: readthedocs
repo_url: http://github.com/phpsci/phpsci-ext
site_url: http://phpsci-carray.readthedocs.io/
site_description: 'Documentation for PHPSci CArray Extension for PHP.'
docs_dir: docs/
dev_addr: '0.0.0.0:8000'

pages:
- Home: index.md
- Initializers:
  - Basic Initializers: initializers.md
  - Range Initializers: range_init.md
  - Random Generators: random.md
- Transformations: transformations.md
- Math:
  - Basic Operations: basic_operations.md
  - Linear Algebra: linear_algebra.md
  - Blas: blas.md
- PHP Array with CArrays: phparray_ops.md
- Performance: performance.md
